# Generated by Django 4.1.7 on 2023-03-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerCommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('reproved', 'reproved'), ('payed', 'payed')], default='new', max_length=30)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sales.order')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltiesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('reproved', 'reproved'), ('payed', 'payed')], default='new', max_length=30)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sales.order')),
            ],
        ),
    ]
